# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  azureSubscription: Contoso

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Dotnet App Publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true
    
- task: AzureWebApp@1
  displayName: Azure Web App Deploy
  inputs:
    azureSubscription: 'Azure subscription 1(79ddd584-fdcc-46f0-a201-914b3822b05a)'
    appType: 'webAppLinux'
    appName: 'dotnet1243'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    runtimeStack: 'DOTNETCORE|3.0'


